<a href="https://colab.research.google.com/github/Abbykairu65/KamiLimu_Assignments/blob/main/Abigail_Kairu_SQL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import sqlite3
import pandas as pd

# Load datasets
athletes = pd.read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-07-27/athlete_events.csv")
regions = pd.read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-07-27/noc_regions.csv")
#sales = pd.read_csv("https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv")
sales = pd.read_csv("https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv", sep='\t')


# Connect to SQLite in-memory DB
conn = sqlite3.connect(":memory:")

# Write DataFrames to SQL tables
athletes.to_sql("athletes_table", conn, index=False, if_exists="replace")
regions.to_sql("regions_table", conn, index=False, if_exists="replace")
sales.to_sql("sales_table", conn, index=False, if_exists="replace")

4622

SECTION 1

number of medals won by each country and show the top 5-athletes ds

In [ ]:
pd.read_sql(
    """
    SELECT NOC, COUNT(*) Medal
    FROM athletes_table
    GROUP BY NOC
    ORDER BY Medal DESC
    LIMIT 5;
    """, conn
)

   NOC  Medal
0  USA  18853
1  FRA  12758
2  GBR  12256
3  ITA  10715
4  GER   9830

average age of athletes who won a Gold medal.

In [ ]:
pd.read_sql(
    """
    SELECT AVG(Age) AS avg_age
    FROM athletes_table;
    """, conn
)

     avg_age
0  25.556898

No of distinct events in each sport

In [ ]:
pd.read_sql(
    """
    SELECT COUNT(DISTINCT Event)
    FROM athletes_table;
    """, conn
)

   COUNT(DISTINCT Event)
0                    765

athletes from the United States (NOC = 'USA')

In [ ]:
pd.read_sql(
    """
    SELECT *
    FROM athletes_table
    WHERE NOC='USA';
    """, conn
)

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
0,6,Per Knut Aaland,M,31.0,188.0,75.0,United States,USA,1992 Winter,1992,Winter,Albertville,Cross Country Skiing,Cross Country Skiing Men's 10 kilometres,None
1,6,Per Knut Aaland,M,31.0,188.0,75.0,United States,USA,1992 Winter,1992,Winter,Albertville,Cross Country Skiing,Cross Country Skiing Men's 50 kilometres,None
2,6,Per Knut Aaland,M,31.0,188.0,75.0,United States,USA,1992 Winter,1992,Winter,Albertville,Cross Country Skiing,Cross Country Skiing Men's 10/15 kilometres Pu...,None
3,6,Per Knut Aaland,M,31.0,188.0,75.0,United States,USA,1992 Winter,1992,Winter,Albertville,Cross Country Skiing,Cross Country Skiing Men's 4 x 10 kilometres R...,None
4,6,Per Knut Aaland,M,33.0,188.0,75.0,United States,USA,1994 Winter,1994,Winter,Lillehammer,Cross Country Skiing,Cross Country Skiing Men's 10 kilometres,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18848,135458,Rami Zur,M,27.0,175.0,77.0,United States,USA,2004 Summer,2004,Summer,Athina,Canoeing,"Canoeing Men's Kayak Doubles, 500 metres",None
18849,135458,Rami Zur,M,31.0,175.0,77.0,United States,USA,2008 Summer,2008,Summer,Beijing,Canoeing,"Canoeing Men's Kayak Singles, 500 metres",None
18850,135458,Rami Zur,M,31.0,175.0,77.0,United States,USA,2008 Summer,2008,Summer,Beijing,Canoeing,"Canoeing Men's Kayak Singles, 1,000 metres",None
18851,135543,"Victor Andrew ""Vic"" Zwolak",M,25.0,175.0,64.0,United States,USA,1964 Summer,1964,Summer,Tokyo,Athletics,"Athletics Men's 3,000 metres Steeplechase",None
18852,135566,"James Francis ""Jim"" Zylker",M,21.0,175.0,75.0,United States,USA,1972 Summer,1972,Summer,Munich,Football,Football Men's Football,None

No of medals awarded each year

In [ ]:
pd.read_sql(
    """
    SELECT Year, COUNT(Medal) as Medal
    FROM athletes_table
    GROUP BY Year;

    """, conn
)

    Year  Medal
0   1896    143
1   1900    604
2   1904    486
3   1906    458
4   1908    831
5   1912    941
6   1920   1308
7   1924    962
8   1928    823
9   1932    739
10  1936   1025
11  1948    987
12  1952   1033
13  1956   1043
14  1960   1058
15  1964   1215
16  1968   1256
17  1972   1414
18  1976   1531
19  1980   1602
20  1984   1698
21  1988   1845
22  1992   2030
23  1994    331
24  1996   1842
25  1998    440
26  2000   2004
27  2002    478
28  2004   2001
29  2006    526
30  2008   2048
31  2010    520
32  2012   1941
33  2014    597
34  2016   2023

athlete records where height or weight is missing

In [ ]:
pd.read_sql(
    """
    SELECT *
    FROM athletes_table
    WHERE Weight IS NULL OR Height IS NULL
    """, conn
)

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
0,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,None
1,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold
2,8,"Cornelia ""Cor"" Aalten (-Strannood)",F,18.0,168.0,NaN,Netherlands,NED,1932 Summer,1932,Summer,Los Angeles,Athletics,Athletics Women's 100 metres,None
3,8,"Cornelia ""Cor"" Aalten (-Strannood)",F,18.0,168.0,NaN,Netherlands,NED,1932 Summer,1932,Summer,Los Angeles,Athletics,Athletics Women's 4 x 100 metres Relay,None
4,10,"Einar Ferdinand ""Einari"" Aalto",M,26.0,NaN,NaN,Finland,FIN,1952 Summer,1952,Summer,Helsinki,Swimming,Swimming Men's 400 metres Freestyle,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64258,135539,Marius Edmund Zwiller,M,18.0,NaN,NaN,France,FRA,1924 Summer,1924,Summer,Paris,Swimming,Swimming Men's 200 metres Breaststroke,None
64259,135542,Werner Zwingli,M,29.0,NaN,NaN,Switzerland,SUI,1956 Winter,1956,Winter,Cortina d'Ampezzo,Cross Country Skiing,Cross Country Skiing Men's 15 kilometres,None
64260,135542,Werner Zwingli,M,29.0,NaN,NaN,Switzerland,SUI,1956 Winter,1956,Winter,Cortina d'Ampezzo,Cross Country Skiing,Cross Country Skiing Men's 4 x 10 kilometres R...,None
64261,135552,Jan (Johann-) Zybert (Siebert-),M,20.0,NaN,NaN,Poland,POL,1928 Summer,1928,Summer,Amsterdam,Cycling,"Cycling Men's Team Pursuit, 4,000 metres",None
64262,135561,Frantiek Zyka,M,26.0,NaN,NaN,Czechoslovakia,TCH,1928 Summer,1928,Summer,Amsterdam,Athletics,Athletics Men's Marathon,None

7. Replace the missing height with the average athlete height

In [ ]:
pd.read_sql(
    """
    SELECT *,
            COALESCE(Height, (SELECT AVG(Height) FROM athletes_table)) AS Height
    FROM athletes_table;
    """,
    conn
)

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal,Height
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,None,180.00000
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,None,170.00000
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,None,175.33897
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold,175.33897
4,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,1988,Winter,Calgary,Speed Skating,Speed Skating Women's 500 metres,None,185.00000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
271111,135569,Andrzej ya,M,29.0,179.0,89.0,Poland-1,POL,1976 Winter,1976,Winter,Innsbruck,Luge,Luge Mixed (Men)'s Doubles,None,179.00000
271112,135570,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014 Winter,2014,Winter,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Individual",None,176.00000
271113,135570,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014 Winter,2014,Winter,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Team",None,176.00000
271114,135571,Tomasz Ireneusz ya,M,30.0,185.0,96.0,Poland,POL,1998 Winter,1998,Winter,Nagano,Bobsleigh,Bobsleigh Men's Four,None,185.00000
271115,135571,Tomasz Ireneusz ya,M,34.0,185.0,96.0,Poland,POL,2002 Winter,2002,Winter,Salt Lake City,Bobsleigh,Bobsleigh Men's Four,None,185.00000

8. Return total sales value per item.

In [ ]:
pd.read_sql(
    """
    SELECT
    item_name,
    SUM(CAST(REPLACE(item_price, '$', '') AS FLOAT) * quantity) AS total_sales
    FROM
    sales_table
    GROUP BY
    item_name;
    """, conn
)

                                item_name  total_sales
0                       6 Pack Soft Drink       369.93
1                           Barbacoa Bowl       672.36
2                        Barbacoa Burrito       894.75
3                   Barbacoa Crispy Tacos       138.71
4                     Barbacoa Salad Bowl       106.40
5                     Barbacoa Soft Tacos       250.46
6                           Bottled Water       649.18
7                                    Bowl        74.00
8                                 Burrito        44.40
9                             Canned Soda       191.84
10                      Canned Soft Drink       603.75
11                          Carnitas Bowl       830.71
12                       Carnitas Burrito       616.33
13                  Carnitas Crispy Tacos        95.94
14                         Carnitas Salad         8.99
15                    Carnitas Salad Bowl        66.34
16                    Carnitas Soft Tacos       375.94
17                           Chicken Bowl      8044.63
18                        Chicken Burrito      6387.06
19                   Chicken Crispy Tacos       524.11
20                          Chicken Salad        81.09
21                     Chicken Salad Bowl      1506.25
22                     Chicken Soft Tacos      1199.01
23                                  Chips       580.34
24           Chips and Fresh Tomato Salsa      1033.96
25                    Chips and Guacamole      2475.62
26      Chips and Mild Fresh Tomato Salsa         3.00
27     Chips and Roasted Chili Corn Salsa        73.75
28     Chips and Roasted Chili-Corn Salsa        43.02
29  Chips and Tomatillo Green Chili Salsa       144.55
30    Chips and Tomatillo Red Chili Salsa       159.30
31  Chips and Tomatillo-Green Chili Salsa        88.43
32    Chips and Tomatillo-Red Chili Salsa        93.21
33                           Crispy Tacos        14.80
34                                   Izze        67.80
35                       Nantucket Nectar       111.87
36                                  Salad        14.80
37                          Side of Chips       290.68
38                             Steak Bowl      2479.81
39                          Steak Burrito      4236.13
40                     Steak Crispy Tacos       375.32
41                            Steak Salad        35.66
42                       Steak Salad Bowl       391.15
43                       Steak Soft Tacos       554.55
44                            Veggie Bowl       901.95
45                         Veggie Burrito      1002.27
46                    Veggie Crispy Tacos         8.49
47                           Veggie Salad        50.94
48                      Veggie Salad Bowl       182.50
49                      Veggie Soft Tacos        90.94

9. Show the top 5 records with the highest item_price.

In [ ]:
pd.read_sql(
    """
    SELECT
    item_name,
    item_price,
    CAST(REPLACE(item_price, '$', '') AS FLOAT) AS item_price_numeric
FROM
    sales_table
ORDER BY
    item_price_numeric DESC
LIMIT 5;

    """, conn
)

                      item_name item_price  item_price_numeric
0  Chips and Fresh Tomato Salsa    $44.25                44.25
1                 Carnitas Bowl    $35.25                35.25
2               Chicken Burrito    $35.00                35.00
3               Chicken Burrito    $35.00                35.00
4                Veggie Burrito    $33.75                33.75

How many unique customer orders are there? (Assume each order_id is a customer.)

In [ ]:
pd.read_sql(
    """
    SELECT COUNT(DISTINCT order_id)
    FROM sales_table;
    """,
    conn
)

   COUNT(DISTINCT order_id)
0                      1834

SECTION 2

Find countries with high-performing athletes in the Olympics. Use at least JOIN, NESTED QUERY, CASE, and optionally WITH.

For each country:

Count the number of athletes who won at least one medal.
Determine the average age of those medalists.
Create a new column called performance:
'High' if average age is below 25
'Medium' if between 25 and 30
'Low' if above 30

In [ ]:
pd.read_sql(
    """
  SELECT
    NOC,
    AVG(Age) AS avg_age,
    CASE
        WHEN AVG(Age) < 25 THEN 'HIGH'
        WHEN AVG(Age) >= 25 AND AVG(Age) <= 30 THEN 'MEDIUM'
        ELSE 'LOW'
    END AS Performance
FROM athletes_table
WHERE Medal >= 1
GROUP BY NOC;
    """,
    conn
)

     NOC    avg_age Performance
0    AFG  23.000000        HIGH
1    AHO  19.000000        HIGH
2    ALG  24.117647        HIGH
3    ANZ  24.068966        HIGH
4    ARG  26.423358      MEDIUM
..   ...        ...         ...
144  VIE  32.750000         LOW
145  WIF  24.000000        HIGH
146  YUG  24.676093        HIGH
147  ZAM  27.000000      MEDIUM
148  ZIM  25.363636      MEDIUM

[149 rows x 3 columns]

In [22]:
pd.read_sql( SIMPLE WAY
    """
SELECT
    a.NOC,
    AVG(a.age) AS avg_age,
    CASE
        WHEN AVG(a.age) < 25 THEN 'High'
        WHEN AVG(a.age) BETWEEN 25 AND 30 THEN 'Medium'
        ELSE 'Low'
    END AS performance
FROM athletes_table a
JOIN (
    SELECT DISTINCT ID
    FROM athletes_table
    WHERE Medal IS NOT NULL
) m ON a.ID = m.ID
GROUP BY a.NOC;
    """,
    conn
)

     NOC    avg_age performance
0    AFG  23.000000        High
1    AHO  19.000000        High
2    ALB  20.000000        High
3    ALG  24.343750        High
4    ANZ  24.150000        High
..   ...        ...         ...
147  VIE  34.166667         Low
148  WIF  24.500000        High
149  YUG  25.196319      Medium
150  ZAM  24.400000        High
151  ZIM  24.838710        High

[152 rows x 3 columns]